config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'posts#index'
  resources :posts do
    resources :comments
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  post_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ActiveRecord::Base
  validates :content, length: { minimum: 1, maximum: 180 }

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id                 :integer          not null, primary key
#  caption            :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  user_id            :integer
#

class Post < ActiveRecord::Base
  validates :image, :user_id, presence: true
  validates :caption, length: { minimum: 3, maximum: 300 }
  has_attached_file :image, styles: { medium: '640x' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime
#  updated_at             :datetime
#  user_name              :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def index
    @comments = @post.comments.order(created_at: :asc)

    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash.now[:error] = 'Error posting comment'
      render root_url
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js
      end
    else
      flash[:error] = "That comment doesn't belong to you!"
      redirect_to root_url
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :own_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order(created_at: :desc).page params[:page]
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'Successfully submitted post.'
      redirect_to @post
    else
      flash.now[:error] = 'Failed to create post.'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = 'Successfully updated post.'
      redirect_to @post
    else
      flash.now[:error] = 'Failed to update post.'
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'Post deleted.'
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def own_post
    unless current_user == @post.user
      flash[:error] = 'Can only edit your own posts!'
      redirect_to root_url
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
  FLASH_TYPES = {
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
  }

  def alert_for(flash_type)
    FLASH_TYPES[flash_type.to_sym] || flash_type.to_s
  end
end

def form_image_select(post)
  if post.image.exists?
    return image_tag post.image.url(:medium),
                     id: 'image-preview',
                     class: 'img-responsive'
  end

  image_tag 'placeholder.png', id: 'image-preview', class: 'img-responsive'
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="user-name"> <%= comment.user.user_name %> </div>
<div class="comment-content"> <%= comment.content %> </div>
<% if comment.user == current_user %>
  <%= link_to post_comment_path(post, comment), method: :delete,
    data: { confirm: "Are you sure?" }, remote: true, id: "delete_#{comment.id}" do %>
      <span class="glyphicon glyphicon-remove delete-comment"></span>
  <% end %>
<% end %>
<br>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/comments/index.html.erb
<%= render @comments, post: @post %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_url %>">Instapic</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to "New Post", new_post_url %> </li>
          <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
        <% else %>
          <li> <%= link_to "Login", new_user_session_path %> </li>
          <li> <%= link_to "Register", new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Instapic</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
   <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <div class="container-fluid">
            <div class="form-group text-center">
              <h4>Upload an image (this is required):</h4>
              <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
            </div>
            <div class="form-group text-center">
              <%= f.input :caption, label: false, placeholder: 'Add your caption' %>
            </div>
            <div class="form-group text-center">
              <%= f.button :submit, class: 'btn-success btn-block' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words post.created_at %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="caption-content">
          <div class="user-name">
            <%= post.user.user_name %>
          </div>
          <%= post.caption %>
        </div>
        <div class="comments" id="comments_<%= post.id %>">
        <% if post.comments.any? %>
          <div class="paginator" id="comments-paginator-<%= post.id %>">
            <% unless post.comments.count <= 4 %>
              <%= link_to "view all #{post.comments.count} comments", post_comments_path(post),
                remote: true,
                class: 'more-comments',
                data: { post_id: "#{post.id}", type: "html" } %>
            <% end %>
          </div>
            <%= render post.comments.last(4), post: post %>
        <% end %>
        </div>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span class="glyphicon glyphicon-heart-empty"></span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...',
          class: "comment_content", id: "comment_content_#{post.id}" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

<div class="text-center edit-links">
  <%= link_to 'Delete', post_url(@post),
    method: :delete,
    data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to 'Cancel', post_url(@post) %>
</div>

app/views/posts/index.html.erb
<div id="posts">
  <%= render @posts %>
</div>


<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render @posts)%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_url %>
    |
    <%= link_to "Edit", edit_post_url(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_url %>
  </div>
<% end %>